blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('frontend.urls', namespace='frontend')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('send/', include('send.urls', namespace='send')),
    path('message/', include('message.urls', namespace='message')),
    path('client/', include('client.urls', namespace='client')),
    path('user/', include('user.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),

        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

params/templates/params/distribution_confirm_delete.html
{% extends 'params/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row text-center">
            <div class="col-6 text-center">
                <div class="card text-center">
                    <div class="card-body text-center">
                        <form method="post">
                            {% csrf_token %}
                            Подтвердить удаление блога {{ object.title }}, с количеством просмотров {{ object.count_view }}
                            <button href="{% url 'blog:list' %}" type="submit" class="button btn btn-success">Подтвердить</button>
                            <a href="{% url "blog:list" %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

params/templates/params/distribution_detail.html
{% extends 'params/base.html' %}
{% block content %}
    {% load my_tags %}
    <div class="col-12">
        <div class="row">
            <div class="container">
                <div class="row">
                    {% csrf_token %}
                        <div class="col-4">
                            <div class="card">
                                <div class="card-body">
                                    <p>{{ object.title }} {{ object.slug }}</p>
                                    <p class="card-text">{{ object.content }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                             <a href="{% url 'blog:view' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">
                                                View {{ object.count_view }}</a>
                                             <a href="{% url 'blog:update' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">
                                                Edite</a>
                                            <a href="{% url 'blog:delete' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">
                                                Delete</a>
                                        </div>
                                    </div>
                                    <p class="text-muted">{{ object.date_created }}</p>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

params/templates/params/distribution_form.html
{% extends 'params/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row text-center">
            <div class="col-6 text-center">
                <div class="card text-center">
                    <div class="card-body text-center">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="button btn btn-success">
                                {% if object %}
                                    Обновить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

params/templates/params/distribution_list.html
{% extends 'params/base.html' %}
{% block content %}
   <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Всего рассылок: {{ object_list|length }}</h1>
      <p class="lead">Количество активных рассылок:{{ ob }}</p>
      <p class="lead">Количество активных рассылок:</p>
    </div>
{% endblock %}