blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('frontend.urls', namespace='frontend')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('send/', include('send.urls', namespace='send')),
    path('message/', include('message.urls', namespace='message')),
    path('client/', include('client.urls', namespace='client')),
    path('user/', include('user.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),

        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logs/urls.py
from client.apps import ClientConfig
from config.urls import path

from client.views import ClientCreateView, ClientDeleteView, ClientDetailView, ClientUpdateView, ClientListView

app_name = ClientConfig.name

urlpatterns = [
    path('', ClientListView.as_view(), name='client_list'),
    path('detail/<int:pk>', ClientDetailView.as_view(), name='client_view'),
    path('update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('delete/<int:pk>', ClientDeleteView.as_view(), name='delete_update'),
    path('create/<int:pk>', ClientCreateView.as_view(), name='delete_update'),
]

send/urls.py
from config.urls import path
from send.apps import SendConfig

from send.views import SendListView, SendCreateView, SendDeleteView, SendDetailView, SendUpdateView

app_name = SendConfig.name

urlpatterns = [
    path('create/', SendCreateView.as_view(), name='create'),
    path('detail/<int:pk>', SendDetailView.as_view(), name='detail'),
    path('update/<int:pk>', SendUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', SendDeleteView.as_view(), name='delete'),
    path('send/', SendListView.as_view(), name='list'),
]

send/models.py
from django.db import models
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}

class Send(models.Model):
    message = models.ForeignKey('message.Message', on_delete=models.CASCADE, verbose_name='сообщение')
    status = models.ForeignKey('status.Status', on_delete=models.CASCADE, verbose_name='статус', default='1')
    period = models.ForeignKey('period.Period', on_delete=models.CASCADE, verbose_name='период')
    time = models.TimeField(verbose_name='Время рассылки', default=timezone.now)

    user = models.ForeignKey('user.User', on_delete=models.CASCADE, verbose_name='user')

    def __str__(self):
        return f'{self.pk} {self.message.theme} {self.status.name} {self.period.name}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылка'
        permissions = [
            (
                'set_status',
                'Can status send'
            )
        ]

send/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from send.models import Send


class SendCreateView(LoginRequiredMixin, CreateView):
    model = Send
    fields = ['period', 'message', 'time', ]
    success_url = reverse_lazy('send:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SendListView(LoginRequiredMixin, ListView):
    model = Send

    def get_queryset(self):
        pk = self.request.user.pk
        queryset = super().get_queryset().filter(user=pk)
        return queryset


class SendDetailView(LoginRequiredMixin, DetailView):
    model = Send

    def get_object(self, queryset=None):
        object = super().get_object(queryset)
        if object.user != self.request.user:
            raise Http404

        return object


class SendUpdateView(LoginRequiredMixin, UpdateView):
    model = Send
    fields = ['status', 'period', 'message', 'time']

    def form_valid(self, form):
        pk = self.kwargs.get('pk')
        self.success_url = reverse_lazy('send:detail', kwargs={'pk': pk})
        return super().form_valid(form)

    def get_object(self, queryset=None):
        object = super().get_object(queryset)
        if object.user != self.request.user:
            raise Http404

        return object


class SendDeleteView(LoginRequiredMixin, DeleteView):
    model = Send
    success_url = reverse_lazy('send:list')

    def get_object(self, queryset=None):
        object = super().get_object(queryset)
        if object.user != self.request.user:
            raise Http404

        return object

send/templates/send/base.html
{% load static %}
{% load my_tags %}
<html lang="en" class="h-100" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Cover Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha38 4-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="apple-touch-icon" href="{% mediapath '/apple-touch-icon.png' %}" sizes="180x180">
    <link rel="icon" href="{% mediapath '/favicon-32x32.png' %}" sizes="32x32" type="image/png">
    <link rel="icon" href="{% mediapath '/favicon-16x16.png' %}" sizes="16x16" type="image/png">
    <link rel="manifest" href="{% mediapath '/manifest.json' %}">
    <link rel="mask-icon" href="{% mediapath '/safari-pinned-tab.svg' %}" color="#7952b3">
    <link rel="icon" href="{{ 'favicon.ico' | mediapath }} ">
    <meta name="theme-color" content="#7952b3">

    {% include 'send/includes/inc_styles.html' %}

<body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0"><a class="link-light"  href="{% url 'send:sends' %}">Главная</a></h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link" href="{% url 'send:create' %}">Создать рассылку</a>
                <a class="nav-link" href="{% url 'client:create' %}">Создать клиента</a>
                <a class="nav-link" href="{% url 'message:create' %}">Создать сообщение</a>
            </nav>
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
        <footer class="mt-auto text-white-50">
           <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link active" aria-current="page" href="{% url 'message:message_list' %}">Сообщения</a>
                <a class="nav-link active" aria-current="page" href="{% url 'client:client_list' %}">Клиенты</a>
                <a class="nav-link active" aria-current="page" href="{% url 'send:send_list' %}">Рассылки</a>
                <a class="nav-link active" aria-current="page" href="#">Логи</a>
            </nav>
        </footer>
</body>

<div class="troywell-avia"></div>
<div class="troywell-caa"></div>
</html>

send/templates/send/list.html
{% extends 'send/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Всего рассылок: {{ object_list|length }}</h1>
        <p class="lead">Количество активных рассылок:{% count_acive object_list %}</p>
        <p class="lead">количество уникальных клиентов для рассылок:{% unique_client object_list %}</p>
    </div>
{% endblock %}

send/templates/send/send_confirm_delete.html
{% extends 'frontend/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="col-12 bg-danger">
            <div class="row text-center">
                <div class="col text-center">
                    <div class="card text-center">
                        <div class="card-body text-center bg-dark">
                            <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                                Подтвердить удаление параметров {{ object }}
                                <button href="{% url 'send:list' %}" type="submit"
                                        class="button btn btn-success">Подтвердить
                                </button>
                                <a href="{% url 'send:detail' object.pk %}" class="btn btn-warning">Отмена</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

send/templates/send/send_detail.html
{% extends 'frontend/base.html' %}
{% block content %}
    {% load my_tags %}
    <div class="col-12">
        <div class="row">
            <div class="container">
                <div class="row">
                    {% csrf_token %}
                    <div class="col-12 bg-danger">
                        <div class="row text-center">
                            <div class="col text-center">
                                <div class="card text-center">
                                    <div class="card-body text-center bg-dark">
                                        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                                            <h3>Параметры рассылки №:{{ object.id }}</h3>
                                            <p class="lead">Пользователь: {{ object.user.email }}</p>
                                            <p class="lead">Статус: {{ object.status }}</p>
                                            <p class="lead">Тема сообщения: {{ object.message }}</p>
                                            <p class="lead">Период: {{ object.period }}</p>
                                            <p class="lead">Время рассылки: {{ object.time }}</p>
                                            <a href="{% url 'send:detail' object.pk %}" type="submit"
                                               class="button btn btn-warning">Посмотреть</a>
                                            <a href="{% url 'send:update' object.pk %}" type="submit"
                                               class="button btn btn-warning">Редактировать</a>
                                            <a href="{% url 'send:delete' object.pk %}" type="submit"
                                               class="button btn btn-warning">Удалить</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

send/templates/send/send_form.html
{% extends 'frontend/base.html' %}
{% block content %}
    <h1>{{ object.client }}</h1>
    <div class="col-12 bg-danger">
        <div class="row text-center">
            <div class="col text-center">
                <div class="card text-center">
                    <div class="card-body text-center bg-dark">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="button btn btn-success">
                                {% if object %}
                                    Обновить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

send/templates/send/send_list.html
{% extends 'frontend/base.html' %}
{% load my_tags %}
{% block content %}
    {% for object in object_list %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h3>Параметры рассылки №:{{ object.id }}</h3>
            <p class="lead">Статус: {{ object.status }}</p>
            <p class="lead">Тема сообщения: {{ object.message }}</p>
            <p class="lead">Время рассылки: {{ object.time }}</p>
            <p class="lead">Пользователь: {{ object.user.email }}</p>
            <a href="{% url 'send:detail' object.pk %}" type="submit" class="button btn btn-warning">Посмотреть</a>
            <a href="{% url 'send:update' object.pk %}" type="submit" class="button btn btn-warning">Редактировать</a>
            <a href="{% url 'send:delete' object.pk %}" type="submit" class="button btn btn-warning">Удалить</a>
            <hr>
        </div>
    {% endfor %}
    <hr>
{% endblock %}