blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('frontend.urls', namespace='frontend')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('send/', include('send.urls', namespace='send')),
    path('message/', include('message.urls', namespace='message')),
    path('client/', include('client.urls', namespace='client')),
    path('user/', include('user.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),

        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from config.urls import path
from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingCreateView, MailingDeleteView, MailingDetailView, \
    MailingUpdateView

app_name = MailingConfig.name

urlpatterns = [
    path('create/', MailingCreateView.as_view(), name='create'),
    path('mailing/', MailingListView.as_view(), name='list'),
    path('detail/<int:pk>', MailingDetailView.as_view(), name='detail'),
    path('update/<int:pk>', MailingUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', MailingDeleteView.as_view(), name='delete'),
]

mailing/models.py
from django.db import models

class Mailing(models.Model):

    client = models.ForeignKey('client.Client', on_delete=models.CASCADE, verbose_name='client')
    send = models.ForeignKey('send.Send', on_delete=models.CASCADE, verbose_name='send')

    user = models.ForeignKey('user.User', on_delete=models.CASCADE, verbose_name='user')

    def __str__(self):
        return f'{self.client} - {self.send}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылка'

mailing/forms.py
from django import forms

from mailing.models import Mailing


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('send', 'client')

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from mailing.forms import MailingForm
from mailing.models import Mailing
from send.models import Send
from services.run_mail import run_mailer

class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        mail_obj = form.save()
        period = mail_obj.send.period.name
        run_mailer(period)
        return super().form_valid(form)



class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):
        pk = self.request.user.pk
        queryset = super().get_queryset()
        if not self.request.user.is_staff:
            queryset = queryset.filter(user=pk)
        return queryset





class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_object(self, queryset=None):
        object = super().get_object(queryset)
        if object.user != self.request.user:
            raise Http404

        return object


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    fields = ['client', 'send']

    def form_valid(self, form):
        pk = self.kwargs.get('pk')
        self.success_url = reverse_lazy('mailing:list', kwargs={'pk': pk})

        return super().form_valid(form)

    def get_object(self, queryset=None):
        object = super().get_object(queryset)
        if object.user != self.request.user:
            raise Http404

        return object


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:list')

    def get_object(self, queryset=None):
        object = super().get_object(queryset)
        if object.user != self.request.user:
            raise Http404

        return object

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'frontend/base.html' %}
{% block content %}
    <div class="col-12 bg-danger">
        <div class="row text-center">
            <div class="col text-center">
                <div class="card text-center">
                    <div class="card-body text-center bg-dark">
                        <form method="post">
                            {% csrf_token %}
                            Подтвердить удаление
                            <p>Со временем: {{ object.send.time }}</p>
                            <p>С темой сообщения: {{ object.send.message.theme }}</p>
                            <p>Со статусом: {{ object.send.status }}</p>
                            <p><button href="{% url 'mailing:list' %}" type="submit" class="button btn btn-success">Подтвердить</button>
                                <a href="{% url 'mailing:list' %}" class="btn btn-warning">Отмена</a></p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'frontend/base.html' %}
{% block content %}
    {% load my_tags %}
    <div class="col-12">
        <div class="row">
            <div class="container">
                <div class="row">
                    {% csrf_token %}
                    <div class="col-12 bg-danger">
                        <div class="row text-center">
                            <div class="col text-center">
                                <div class="card text-center">
                                    <div class="card-body text-center bg-dark">
                                        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                                            <h3>Номер:{{ object.id }}</h3>
                                            <p class="lead">Тема: {{ object.send.message.them }}</p>
                                            <p class="lead">Текст: {{ object.send.message.message }}</p>
                                            <p class="lead">Время: {{ object.send.time }}</p>
                                            <p class="lead">Статус: {{ object.send.status.name }}</p>
                                            <p class="lead">Период: {{ object.send.period.name }}</p>
                                            <p class="lead">Клиент: {{ object.client.email }}</p>
                                            <a href="{% url 'mailing:detail' object.pk %}" type="submit"
                                               class="button btn btn-warning">Посмотреть</a>
                                            <a href="{% url 'mailing:update' object.pk %}" type="submit"
                                               class="button btn btn-warning">Редактировать</a>
                                            <a href="{% url 'mailing:delete' object.pk %}" type="submit"
                                               class="button btn btn-warning">Удалить</a>
                                            <hr>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'frontend/base.html' %}
{% block content %}
    <div class="col-12 bg-danger">
        <div class="row text-center">
            <div class="col text-center">
                <div class="card text-center">
                    <div class="card-body text-center bg-dark">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="button btn btn-success">
                                {% if object %}
                                    Обновить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'frontend/base.html' %}
{% load my_tags %}
{% block content %}
    {% for object in object_list %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h3>Отправление №:{{ object.id }}</h3>
            <p class="lead">ФИО: {{ object.client }}</p>
            <p class="lead">Почта: {{ object.client.email }}</p>
            <p class="lead">Статус: {{ object.send.status }}</p>
            <p class="lead">Тема сообщения: {{ object.send.message }}</p>
            <p class="lead">Период: {{ object.send.period }}</p>
            <p class="lead">Время рассылки: {{ object.send.time }}</p>
            <a href="{% url 'send:detail' object.pk %}" type="submit" class="button btn btn-warning">Посмотреть</a>
            <a href="{% url 'send:update' object.pk %}" type="submit" class="button btn btn-warning">Редактировать</a>
            <a href="{% url 'send:delete' object.pk %}" type="submit" class="button btn btn-warning">Удалить</a>
            <hr>
        </div>
    {% endfor %}
    <hr>
    <hr>
{% endblock %}