blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('frontend.urls', namespace='frontend')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('send/', include('send.urls', namespace='send')),
    path('message/', include('message.urls', namespace='message')),
    path('client/', include('client.urls', namespace='client')),
    path('user/', include('user.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),

        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from config.urls import path
from frontend.apps import FrontendConfig
from frontend.views import index_view

app_name = FrontendConfig.name

urlpatterns = [
    path('', index_view, name='index_view')
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from user.apps import UserConfig
from user.views import RegistertView, UserProfileView, check_email, password, UserListView, UserDeleteView

app_name = UserConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegistertView.as_view(), name='register'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('check_email/', check_email, name='check_email'),
    path('password/', password, name='password'),
    path('users/', UserListView.as_view(), name='list'),
    path('delete/<int:pk>', UserDeleteView.as_view(), name='delete'),
]

frontend/models.py
from django.db import models

# Create your models here.

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None

    phone = models.CharField(max_length=50, verbose_name='Phone', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Avatar', **NULLABLE)
    country = models.CharField(max_length=150, verbose_name='Country', **NULLABLE)

    email = models.EmailField(verbose_name='Email', unique=True)
    check_email = models.BooleanField(default=False, verbose_name='Check')
    verify_number = models.CharField(max_length=150, verbose_name='verify_number', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            (
                'view_users',
                'Can view users'
            ),
        ]

frontend/views.py
from django.shortcuts import render

from mailing.models import Mailing

def index_view(request):
    context = {}
    pk = request.user.pk
    context['object_list'] = Mailing.objects.filter(user=pk).all()
    return render(request, 'frontend/list.html', context)

frontend/templates/frontend/base.html
{% load static %}
{% load my_tags %}
<html lang="en" class="h-100" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Cover Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha38 4-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="apple-touch-icon" href="{% mediapath '/apple-touch-icon.png' %}" sizes="180x180">
    <link rel="icon" href="{% mediapath '/favicon-32x32.png' %}" sizes="32x32" type="image/png">
    <link rel="icon" href="{% mediapath '/favicon-16x16.png' %}" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="{% mediapath '/safari-pinned-tab.svg' %}" color="#7952b3">
    <link rel="icon" href="{{ 'favicon.ico' | mediapath }} ">
    <meta name="theme-color" content="#7952b3">

    {% include 'frontend/includes/inc_styles.html' %}

<body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <h3 class="float-md-start mb-0"><a class="link-light" href="{% url 'frontend:index_view' %}">Главная</a>
    </h3>
    <hr>
    <h3 class="float-md-start mb-0"><a class="link-light" href="{% url 'blog:list' %}">Blog</a>
    </h3>
    <header class="mb-auto">

        <div>


            <nav class="nav nav-masthead justify-content-center float-md-end">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{%  url 'user:logout' %}">Выйти</a>
                <a class="nav-link" href="{%  url 'user:profile' %}">Профиль</a>
                <a class="nav-link" href="{% url 'mailing:create' %}">Создать рассылку</a>
                <a class="nav-link" href="{% url 'send:create' %}">Параметры рассылки</a>
                <a class="nav-link" href="{% url 'client:create' %}">Создать клиента</a>
                <a class="nav-link" href="{% url 'message:create' %}">Создать сообщение</a>
                <a class="nav-link" href="{% url 'blog:create' %}">Создать блог</a>
                {% else %}
                <a class="nav-link" href="{%  url 'user:login' %}">Войти</a>
                <a class="nav-link" href="{%  url 'user:register' %}">Регистрация</a>
                {% endif %}
            </nav>
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer class="mt-auto text-white-50">
        <nav class="nav nav-masthead justify-content-center float-md-end">
            {% if user.is_authenticated %}
            <a class="nav-link active" aria-current="page" href="{% url 'mailing:list' %}">Рассылки</a>
            <a class="nav-link active" aria-current="page" href="{% url 'message:list' %}">Сообщения</a>
            <a class="nav-link active" aria-current="page" href="{% url 'client:list' %}">Клиенты</a>
            <a class="nav-link active" aria-current="page" href="{% url 'send:list' %}">Параметры</a>
            <a class="nav-link active" aria-current="page" href="#">Логи</a>
            {% endif %}
            {% if perms.user.view_user %}
            <a class="nav-link active" aria-current="page" href="{% url 'user:list' %}">Пользователи</a>
            {% endif %}
        </nav>
    </footer>
</body>
<div class="troywell-avia"></div>
<div class="troywell-caa"></div>
</html>

frontend/templates/frontend/list.html
{% extends 'frontend/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Всего рассылок: {{ object_list|length }}</h1>
        <p class="lead">Количество активных рассылок:{% count_acive object_list %}</p>
        <p class="lead">количество уникальных клиентов для рассылок:{% unique_client object_list %}</p>
    </div>
                    {% if user.is_authenticated %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <p class="lead">Количество активных рассылок:{% count_acive object_list %}</p>
    </div>
        {% endif %}
{% endblock %}